# This builds the Docker image from the specified directory on all the
# platforms and do a basic sanity check to verify that Nomad runs.
name: Build

on:
  workflow_call:
    inputs:
      directory:
        description: Directory where the Dockerfile is
        required: true
        type: string

      platforms:
        description: The platforms to build on
        required: true
        type: string

jobs:
  prepare:
    name: Prepare Build Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.platforms.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Create matrix
        id: platforms
        run: |
          echo "matrix=$(echo '"${{ inputs.platforms }}"' | jq -cr '. / ","')" >> "$GITHUB_OUTPUT"

      - name: Show matrix
        run: |
          echo ${{ steps.platforms.outputs.matrix }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - prepare

    strategy:
      fail-fast: false

      matrix:
        platforms: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v5

      - name: Metadata
        id: meta
        working-directory: ${{ inputs.directory }}
        run: |
          echo "nomad=$(cat nomad-version)" >> "$GITHUB_OUTPUT"
          echo "dockerfile=${{ inputs.directory }}/Dockerfile" >> "$GITHUB_OUTPUT"

      - name: Lint the Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ steps.meta.outputs.dockerfile }}

      - name: Set up QEMU
        id: docker-setup
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.platforms }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.directory }}
          file: ${{ steps.meta.outputs.dockerfile }}
          load: true  # load the image built locally for later use
          build-args: |-
            NOMAD_VERSION=${{ steps.meta.outputs.nomad }}
          platforms: ${{ matrix.platforms }}
          push: false
          tags: local/nomad:test

      - name: Test
        run: make test DOCKER_TAG=local/nomad:test
