name: "v1.6.x: release"

on:
  push:
    tags:
      - 1.6.**

jobs:
  release:
    name: Release
    permissions:
      contents: write
      packages: write
      discussions: write
    uses: ./.github/workflows/template-release.yml
    secrets: inherit
    with:
      platforms: linux/amd64
      directory: v1.6.x
