name: "v2.0.x: build"

on:
  push:
    branches:
      - main
    paths:
      - v2.0.x/**

  pull_request:
    branches:
      - main
    paths:
      - v2.0.x/**

jobs:
  test:
    name: Test
    uses: ./.github/workflows/template-build.yml
    with:
      platforms: linux/amd64,linux/arm64
      directory: v2.0.x
