name: "v2.0.x: create tag"

on:
  push:
    branches:
      - main

    paths:
      - v2.0.x/nomad-version

jobs:
  tag:
    name: Tag
    permissions:
      contents: write
    uses: ./.github/workflows/template-create-tag.yml
    secrets: inherit
    with:
      directory: v2.0.x
